version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: esbuild
    versions:
    - 0.11.0
    - 0.11.5
    - 0.11.9
    - 0.8.34
    - 0.8.39
    - 0.8.43
    - 0.8.46
    - 0.8.50
    - 0.8.54
    - 0.8.57
    - 0.9.2
    - 0.9.6
  - dependency-name: rollup
    versions:
    - 2.41.2
